---
- name: Converge
  hosts: all
  become: true

  vars:
    - make_cmd: 'make -s install'

  pre_tasks:

    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false

    - name: "Installing Rsync"
      apt: >
        pkg={{ item }}
        state=latest
        update_cache=yes
        cache_valid_time=3600
      with_items:
        - rsync

    - name: make | install make
      apt:
        pkg: make
        state: present

  roles:
    - role: ansible-role-csrmake
