---
- name: Converge
  hosts: all
  become: true

  vars:
    - make_cmd: 'make -s install'

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false

    - name: rsync | install rsync
      apt:
        pkg: rsync
        state: present

    - name: make | install make
      apt:
        pkg: make
        state: present

  roles:
    - role: ansible-role-csrmake
